spring.application.name=web-constructora

# Conexión a la Base de Datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_construccion?serverTimezone=UTC&useSSL=false
spring.datasource.username=root

# Contraseña para entrar a MySQL Workbench
spring.datasource.password=admin

# Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
# 'update' creará las tablas automáticamente en Workbench basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de Spring Boot el SQL que se ejecuta detrás de escena
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true